requires 'Config::IniFiles', '>= 3.000003, < 3.000004';
requires 'Term::ANSIColor', '>= 5.01, < 5.02';
requires 'DBI', '>= 1.643';
requires 'DBD::mysql', '>= 4.050';
requires 'Mojolicious::Lite';
requires 'FindBin';
requires 'Text::ParseWords';
requires 'DateTime::Format::MySQL';
requires 'DATA::Dumper';
requires 'App::Coloris';